title: devlopr jekyll
subtitle: A Jekyll Theme built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  A Jekyll Theme Built For Developers
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devlopr.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: sujay-kundu  #for comments using disqus
author: devlopr
author_bio: devlopr-jekyll is a theme built for developers. Anyone can create a blog like this. As easy as PIE !
author_email: "sujaykundu777@gmail.com"
author_location: India
author_website_url: "https://sujaykundu.com"

# social links
twitter_username: sujaykundu777
github_username:  sujaykundu777
facebook_username: sujay.kundu2
linkedin_username: sujaykundu
behance_username: sujaykundu
instagram_username: sujaykundu777
medium_username: sujaykundu
telegram_username: yourusername
dribbble_username: yourusername 
flickr_username: yourusername

# dont touch this unless required
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll-algolia
  - jekyll-menus 


# code highlighter
highlighter: rouge

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-46783401-10      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# minify html
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

