title: Tello-Vision
subtitle: The Portfolio of Joshua "Tello-" Lollis.
description: >- # this means to ignore newlines until "baseurl:"
  Here you will find info about me as well as my blog, art, music and projects!
  

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: CV
      url: /cv
    - text: About
      url: /about
    - text: Projects
      url: /projects
    - text: Art
      url: /art
    - text: Music
      url: /music
    - text: Blog
      url: /blog
    - text: Contact
      url : /contact

#    - text: AI Detection
#      url: /ai-detection
#   - text: Shop
#     url : /shop
#   - text: Unity Engine
#     url : /unity


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: me-t.png
author: Josh Lollis
author_bio: Hi, my name is Josh! I love creating! I hope you find something that inspires you here. :D
author_email: "lollisjosh@csu.fullerton.edu"
author_location: Fullerton CA, USA
author_website_url: "https://telloviz.netlify.app"
typewrite-text: Game Developer | Programmer | Artist | Musician | Composer
hero_cover_img: office.png # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Brain Builders Stem Education
              company_logo: brain.png
              company_url: https://www.brainbuildersed.org
              designation: Educator
              description: Engineering Educator for 3rd-6th grade students in after school programs around the Santa Ana CA area.
              visibility: true
            - company_name: Thales
              company_logo: thales.png
              company_url: https://www.thalesgroup.com/en
              designation: Production Team Assistant
              description: Quality Assurance on Digital Video/Audio assets per spec to client contract.
              visibility: true
            - company_name: ADI / Honeywell / Resideo
              company_logo: adi.png
              company_url: https://www.adiglobaldistribution.us
              designation: Sales Asistant / Will-Call Lead
              description: Order Pulling, Warehouse Logistics, Will-Call Window Lead
              visibility: true
            - company_name: Wal*Mart
              company_logo: wallyworld.png
              company_url: https://walmart.com
              designation: Electronics Sales / Photo Lab Tech
              description: Worked most departments over 6 years.
              visibility: true


# Education
author_education_details:
              - college_logo: csuf.png
                college_name: California State University Fullerton
                college_url: https://www.fullerton.edu
                college_degree: Computer Science
                description: Bachelor of Science (Spring 2025)
                visibility: true
              - college_logo: fullcoll.png
                college_name: Fullerton College
                college_url: https://www.fullcoll.edu
                college_degree: Computer Science
                description: Associate of Science 
                visibility: true

# Projects
author_project_details: 
              - project_thumbnail: snake-logo.png
                project_title: Snake
                project_description: Snake built in C++ using SFML w/ art by me
                project_url: https://telloviz.netlify.app/gallery/snake
                visibility: true
              - project_thumbnail: surfer-t.PNG
                project_title: Neon Cloud
                project_description: Summer mentorship project in Unity Engine
                project_url: https://telloviz.netlify.app/projects/neoncloud
                visibility: true
              - project_thumbnail: editor.PNG
                project_title: TCG Editor Window
                project_description: Custom Unity Editor Rest Interface
                project_url: https://telloviz.netlify.app/projects/editor
                visibility: true
              - project_thumbnail: lander.png
                project_title: Lunar Lander
                project_description: A modern Lunar Lander in Unity
                project_url: https://telloviz.netlify.app/projects/lunar
                visibility: true


# social links
twitter_username: 
github_username:  TelloViz
facebook_username: 
linkedin_username: lollisjosh
behance_username: 
instagram_username: 
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 

# for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: tello-vision
# hyvor_talk_website_id: 9321

# wakatime username (coding activity)
wakatime_username: "telloviz"

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: "" # https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: d4103f46-9fbd-4438-9eee-5337432dd46e
formspree_email: f/meqbalrl

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# Google Analytics
google_analytics: G-GX0M7D7MJR


# syntax highlighter
markdown: kramdown

highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "projects"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: "art"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: "music"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-pdf-embed

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"

# include:
#   - NeonCloud/Bulid


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
